version: 2.1

jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.0.4
    environment:
      TF_VAR_app_name: 'myapp'
      TF_VAR_env: 'stage2'
      TF_VAR_region: 'us-east-1'
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
          working_directory: ./terraform
      - run:
          name: Apply Terraform Plan
          command: terraform apply -auto-approve
          working_directory: ./terraform