version: 2.1

jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.0.4
    environment:
      TF_VAR_app_name: $TF_VAR_app_name
      TF_VAR_env: $TF_VAR_env
      TF_VAR_region: 'us-east-1'
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
          working_directory: ./terraform
          environment:
            TF_VAR_app_name: $TF_VAR_app_name
            TF_VAR_env: $TF_VAR_env
            TF_VAR_region: 'us-east-1'
          
      - run:
          name: Apply Terraform Plan
          command: terraform apply -auto-approve
          working_directory: ./terraform
          environment:
            TF_VAR_app_name: $TF_VAR_app_name
            TF_VAR_env: $TF_VAR_env
            TF_VAR_region: 'us-east-1'