version: 2.1

jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.0.4
    working_directory: ./terraform
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Apply Terraform Plan
          command: terraform apply -auto-approve
